services:
  - type: web
    name: youtube-downloader
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    healthCheckPath: /health
    autoDeploy: true
    plan: free 
